services:
  api-gateway:
    build: ./api-gateway
    depends_on:
      - backend1
      - backend2
      - backend3
      - notification
    networks:
      - backend-network
    ports:
      - "8080:8080"

  backend1:
    build: ./backend1
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=backend_db
      - DB_PORT=3306
    depends_on:
      - mysql
      - kafka
    networks:
      - backend-network
    ports:
      - "5001:5001"

  backend2:
    build: ./backend2
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=backend_db
    depends_on:
      - mysql
      - kafka
    networks:
      - backend-network
    ports:
      - "5002:5002"

  backend3:
    build: ./backend3
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=backend_db
    depends_on:
      - mysql
      - kafka
    networks:
      - backend-network
    ports:
      - "5003:5003"

  notification:
    build: ./notification
    depends_on:
      - kafka
    networks:
      - backend-network
    ports:
      - "5004:5004"

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=backend_db
    ports:
      - "3307:3306"
    networks:
      - backend-network

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - backend-network
    ports:
      - "9092:9092"

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - backend-network
    ports:
      - "2181:2181"

networks:
  backend-network:
    driver: bridge